### ISSUE TITLE
Write rules

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-client#80]

**Comment by COrtsJosep** [comment]
There were problems with the autolinking. I'll link by hand.

**Comment by COrtsJosep** [comment]
5f23e7d1faccc237769768cbb4cc1a958dbea710

**Comment by COrtsJosep** [comment]
65fe39e533b9a5b628bfb4c57971e5fdf5807f6f

**Comment by COrtsJosep** [comment]
fdaa99006a14264f3fb3d9d73f213781cbd40fab
