### ISSUE TITLE
Add "rules" button to dashboard & and make it link to rules page

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-client#81]

**Comment by COrtsJosep** [comment]
Again problems with the autolink, I'll fill in what I can by hand.

**Comment by COrtsJosep** [comment]
fdaa99006a14264f3fb3d9d73f213781cbd40fab

**Comment by COrtsJosep** [comment]
635a2882fd3282f4f990afec83368086fe557a47

**Comment by COrtsJosep** [comment]
560bc04c3a112074c16a432ae1c91b0c6bfba39b
