### ISSUE TITLE
Implement option to abandon room anytime, and immediate redirection to the dashboard.

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-client#99]

**Comment by c-b123** [comment]
done

**Comment by cedric-vr** [comment]
d063de91, 6d4edc45

**Comment by COrtsJosep** [comment]
d063de91f5745d4e9a8cacd46a5d66a3b51d9743
6d4edc45efb8179f12964eae01da7ae8cbad66ee

The issue was that it was in the server, not in the client.
